### ISSUE TITLE
 'Non-existent config key: loss'

### ISSUE THREAD

**Issue by nosaywood** [YufeiWang777/LRRU#23]
Traceback (most recent call last):
  File "train_apex.py", line 8, in <module>
    config = get_cfg(arg)
  File "/data/home/2023/wangbingqi/RGBD/LRRU/configs/__init__.py", line 13, in get
    cfg.merge_from_file('configs/' + arg.configuration)
  File "/data/home/2023/wangbingqi/miniconda3/envs/lrru/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/data/home/2023/wangbingqi/miniconda3/envs/lrru/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/data/home/2023/wangbingqi/miniconda3/envs/lrru/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: loss'
您好，想请教您一下这个问题，报错如上

**Comment by zhengyu2023** [comment]
你好我也有同样的问题，你解决了吗

**Comment by zzz-0930** [comment]
请问你们解决了吗

**Comment by chuanqi1997** [comment]
**The same problem：**
server@server:~/Work/LRRU$ python train_apex.py -c train_lrru_mini_kitti.yml
Traceback (most recent call last):
  File "train_apex.py", line 8, in <module>
    config = get_cfg(arg)
  File "/home/server/Work/LRRU/configs/__init__.py", line 13, in get
    cfg.merge_from_file('configs/' + arg.configuration)
  File "/home/server/miniconda3/envs/DenseLiDAR/lib/python3.8/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/server/miniconda3/envs/DenseLiDAR/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/server/miniconda3/envs/DenseLiDAR/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: loss'

**Comment by chuanqi1997** [comment]
in config.py file add:
line 113:
cfg.loss = '1.0*L1+1.0*L2'
